GET http://localhost:3000/articles/b8f11e76-0a9e-4b3f-bccf-8d9b4fbf331e

###

GET http://localhost:3000/articles

###

GET http://localhost:3000/search?q=판다

###

POST http://localhost:3000/articles
Content-Type: application/json

{
    "title": "판다마켓 테스트",
    "content": "판다마켓 부시기"
}

###

PATCH http://localhost:3000/articles/22111729-eaad-46e3-8298-be2cec93cfe9
Content-Type: application/json

{
  "title": "댓글 수정",
  "content": "댓글 수정해봐요."
}

###

DELETE http://localhost:3000/articles/52c467eb-df4d-4835-bdfa-c46ecacefb5d
